//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AYAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSizePric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemSizePric()
        {
            this.Orderdetals = new HashSet<Orderdetal>();
        }
    
        public int ItemSizePricID { get; set; }
        public int ItemID { get; set; }
        public int SizeID { get; set; }
        public double pric { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetal> Orderdetals { get; set; }
    }
}
