//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AYAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetal
    {
        public int OrderdetalsID { get; set; }
        public int ItemSizePriceID { get; set; }
        public int Quontity { get; set; }
        public double Price { get; set; }
        public int OrderID { get; set; }
    
        public virtual ItemSizePric ItemSizePric { get; set; }
        public virtual Order Order { get; set; }
    }
}
