//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AYAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orderdetals = new HashSet<Orderdetal>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public string TrxnStatus { get; set; }
        public Nullable<System.DateTime> Checkout { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetal> Orderdetals { get; set; }
        public virtual User User { get; set; }
    }
}
